import type { Config } from "tailwindcss";

const withOpacity = (variableName: string) => `rgb(var(${variableName}) / <alpha-value>)`;

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffa8a3",
        "on-secondary": withOpacity("--on-secondary"),
        "surface-variant": withOpacity("--surface-variant"),
        "surface-tint": "#53ddfc",
        "secondary": withOpacity("--secondary"),
        "on-primary-fixed-variant": "#005564",
        "surface-dim": withOpacity("--surface-dim"),
        "on-surface": withOpacity("--on-surface"),
        "error": "#ff716c",
        "tertiary-dim": "#6b9cfe",
        "surface": withOpacity("--surface"),
        "surface-bright": withOpacity("--surface-bright"),
        "primary-container": withOpacity("--primary-container"),
        "background": withOpacity("--background"),
        "inverse-surface": "#faf8ff",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#40009b",
        "on-surface-variant": withOpacity("--on-surface-variant"),
        "secondary-container": withOpacity("--secondary-container"),
        "primary-dim": withOpacity("--primary-dim"),
        "surface-container-low": withOpacity("--surface-container-low"),
        "tertiary-fixed": "#8bb0ff",
        "primary-fixed-dim": "#40ceed",
        "on-tertiary": "#002355",
        "surface-container-high": withOpacity("--surface-container-high"),
        "surface-container-lowest": withOpacity("--surface-container-lowest"),
        "tertiary-container": "#6294f6",
        "on-secondary-container": withOpacity("--on-secondary-container"),
        "on-primary-fixed": "#003640",
        "outline": withOpacity("--outline"),
        "inverse-primary": "#00687b",
        "outline-variant": withOpacity("--outline-variant"),
        "surface-container-highest": withOpacity("--surface-container-highest"),
        "inverse-on-surface": "#4d556b",
        "on-background": withOpacity("--on-background"),
        "secondary-dim": withOpacity("--secondary-dim"),
        "on-primary": withOpacity("--on-primary"),
        "tertiary": "#74a2ff",
        "error-container": "#9f0519",
        "tertiary-fixed-dim": "#74a2ff",
        "on-error": "#490006",
        "on-tertiary-fixed-variant": "#00367c",
        "on-tertiary-fixed": "#00163b",
        "surface-container": withOpacity("--surface-container"),
        "primary": withOpacity("--primary"),
        "on-primary-container": withOpacity("--on-primary-container"),
        "secondary-fixed": "#dac9ff",
        "on-tertiary-container": "#00153a",
        "secondary-fixed-dim": "#ceb9ff",
        "primary-fixed": "#53ddfc",
        "on-secondary-fixed-variant": "#5f28c8"
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ["JetBrains Mono"]
      },
    },
  },
  plugins: [],
};
export default config;
