import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffa8a3",
        "on-secondary": "#280067",
        "surface-variant": "#192540",
        "surface-tint": "#53ddfc",
        "secondary": "#ac8aff",
        "on-primary-fixed-variant": "#005564",
        "surface-dim": "#060e20",
        "on-surface": "#dee5ff",
        "error": "#ff716c",
        "tertiary-dim": "#6b9cfe",
        "surface": "#060e20",
        "surface-bright": "#1f2b49",
        "primary-container": "#21bedc",
        "background": "#060e20",
        "inverse-surface": "#faf8ff",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#40009b",
        "on-surface-variant": "#a3aac4",
        "secondary-container": "#5516be",
        "primary-dim": "#40ceed",
        "surface-container-low": "#091328",
        "tertiary-fixed": "#8bb0ff",
        "primary-fixed-dim": "#40ceed",
        "on-tertiary": "#002355",
        "surface-container-high": "#141f38",
        "surface-container-lowest": "#000000",
        "tertiary-container": "#6294f6",
        "on-secondary-container": "#d9c8ff",
        "on-primary-fixed": "#003640",
        "outline": "#6d758c",
        "inverse-primary": "#00687b",
        "outline-variant": "#40485d",
        "surface-container-highest": "#192540",
        "inverse-on-surface": "#4d556b",
        "on-background": "#dee5ff",
        "secondary-dim": "#8455ef",
        "on-primary": "#004b58",
        "tertiary": "#74a2ff",
        "error-container": "#9f0519",
        "tertiary-fixed-dim": "#74a2ff",
        "on-error": "#490006",
        "on-tertiary-fixed-variant": "#00367c",
        "on-tertiary-fixed": "#00163b",
        "surface-container": "#0f1930",
        "primary": "#53ddfc",
        "on-primary-container": "#00343e",
        "secondary-fixed": "#dac9ff",
        "on-tertiary-container": "#00153a",
        "secondary-fixed-dim": "#ceb9ff",
        "primary-fixed": "#53ddfc",
        "on-secondary-fixed-variant": "#5f28c8"
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ["JetBrains Mono"]
      },
    },
  },
  plugins: [],
};
export default config;
