"""exercise_add_language_tags_nullable_chapter

Revision ID: 9408a82f8774
Revises: 67df796ec4f9
Create Date: 2026-03-22 20:29:47.350401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9408a82f8774'
down_revision: Union[str, Sequence[str], None] = '67df796ec4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('language', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('exercises', 'chapter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_exercises_language'), 'exercises', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_language'), table_name='exercises')
    op.alter_column('exercises', 'chapter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('exercises', 'tags')
    op.drop_column('exercises', 'language')
    # ### end Alembic commands ###
